### ISSUE TITLE
I forgot my password for Authme. Help!

### ISSUE THREAD

**Issue by panichol227** [Levminer/authme#195]

**Comment by panichol227** [comment]
I forgot my password on Authme. What next?

**Comment by Levminer** [comment]
What version are you using?

**Comment by panichol227** [comment]
Lorik, thank you. Version - 3.1.1

**Comment by Levminer** [comment]
Well, if you don't have a backup key (whice was removed in 3.0.0, but skill can be used) there is nothing you can do, you have to guess your password (Authme will block you every 5 try for 5 seconds, but you will not be blocked). And there is nothing I can do, because your codes are protected by your password.

Or I hope you have a backup of the import file (which you used to import your codes).

**Comment by panichol227** [comment]
Oh well.
